# Generated by Django 5.2.3 on 2025-06-20 18:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genero', '0002_alter_genero_descricao'),
        ('serie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='ano_lancamento',
            field=models.PositiveIntegerField(default=2025, validators=[django.core.validators.MinValueValidator(1928), django.core.validators.MaxValueValidator(2030)], verbose_name='Ano de Lançamento'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='idGenero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='genero.genero', verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Título da série'),
        ),
    ]
