version: '3.8'

services:
  web:
    build: .
    ports:
      - '8000:8000'
    volumes:
      # Volume para desenvolvimento - permite editar código sem rebuild
      - .:/app
      # Volume para persistir dados do SQLite
      - sqlite_data:/app/db
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=jackflixweb.settings
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  sqlite_data:
