# Generated by Django 5.2.3 on 2025-06-20 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='ano_lancamento',
            field=models.PositiveIntegerField(default=2025, validators=[django.core.validators.MinValueValidator(1895), django.core.validators.MaxValueValidator(2030)], verbose_name='Ano de Lançamento'),
        ),
    ]
